// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CMenuAside: typeof import('./src/components/c-menu-aside.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    Home: typeof import('./src/views/home.vue')['default']
    IconHerosHome: typeof import('~icons/heroicons-outline/home')['default']
    IconHerosMenu: typeof import('~icons/heroicons-outline/menu')['default']
    IconHerosUser: typeof import('~icons/heroicons-outline/user')['default']
    IconHerosUsers: typeof import('~icons/heroicons-outline/users')['default']
    IconHerosXCircle: typeof import('~icons/heroicons-outline/x-circle')['default']
    IconLocalAdd: typeof import('~icons/local/add')['default']
    IconLocalCptm: typeof import('~icons/local/cptm')['default']
    IconLocalList: typeof import('~icons/local/list')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    User: typeof import('./src/views/user.vue')['default']
    UserAdd: typeof import('./src/views/user-add.vue')['default']
    UserList: typeof import('./src/views/user-list.vue')['default']
    VButton: typeof import('./src/components/v-button.vue')['default']
    VCardHome: typeof import('./src/components/v-card-home.vue')['default']
    VFooter: typeof import('./src/components/v-footer.vue')['default']
    VHeader: typeof import('./src/components/v-header.vue')['default']
    VInput: typeof import('./src/components/v-input.vue')['default']
    VListUsers: typeof import('./src/components/v-list-users.vue')['default']
    VLoaderCircle: typeof import('./src/components/v-loader-circle.vue')['default']
    VMenu: typeof import('./src/components/v-menu.vue')['default']
    VMenuAside: typeof import('./src/components/v-menu-aside.vue')['default']
    VMenuAsideButton: typeof import('./src/components/v-menu-aside-button.vue')['default']
    VMenuItem: typeof import('./src/components/v-menu-item.vue')['default']
    VPage: typeof import('./src/components/v-page.vue')['default']
  }
}

export { }
